### ISSUE TITLE
encode_features and calculate_feature_matrix use different dtypes for boolean features

### ISSUE THREAD

**Issue by hawksung1** [FeatureLabs/featuretools#1027]
### Bug/Feature Request Title
saving features after encode_features and load type issue
-----
#### Bug/Feature Request Description
encode_features purpose = make categorical column to number

when I run code
`result, features = ft.encode_features(result, features, **encode_options)`
I get result with **0 or 1** with type **uint8**(categorical type column changed to uint8)

but after
`ft.save_features(features, self.generator_file_path)`

and run
`load_features = ft.load_features(load_features_path)`
`ft.calculate_feature_matrix(load_features, **load_options)`

then I got result **True or False** which is **boolean type**(categorical type column changed to boolean)

I guess It is problem of **encode_features**
because when I run 
`result, features = ft.encode_features(result, features, **encode_options)`
I got **features variable** type **class 'featuretools.variable_types/variable/Boolean'**
but the **result** table with **uint8 0 or 1** column

#### Expected Output
It should be uint8 type 0 or 1 column eventhough I save features and load them
encode_features result should be kept with type number

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 0.16.0
Featuretools installation directory: /home/test/PycharmProjects/test/venv/lib/python3.6/site-packages/featuretools

SYSTEM INFO
-----------
python: 3.6.9.final.0
python-bits: 64
OS: Linux
OS-release: 5.3.0-53-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: ko_KR.UTF-8
LOCALE: ko_KR.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.15.4
pandas: 1.0.1
tqdm: 4.46.0
PyYAML: 3.13
cloudpickle: 0.8.0
dask: 2.8.1
distributed: 2.16.0
psutil: 5.6.3
Click: 7.0
pip: 20.0.2
setuptools: 44.1.0

</details>

**Comment by rwedge** [comment]
@hawksung1 , thanks for the bug report!

I think the core issue here is that `encode_feature_matrix` uses unit8 dtype for boolean features but `calculate_feature_matrix` uses bool dtype

**Comment by rwedge** [comment]
Fixed by #1082
