### ISSUE TITLE
Document how to add custom variable types

### ISSUE THREAD

**Issue by rohan-gt** [FeatureLabs/featuretools#1063]
Not sure if this has already been implemented but is there a way to define custom variable types (eg. Age, Height, Weight etc.) similar to how custom primitives are defined?

**Comment by gsheni** [comment]
Yes, there is a way to define custom variable types:

For example, let's create a custom Age Variable Type.

```python
from featuretools.variable_types import Variable

class Age(Variable):
    _default_pandas_dtype = float
```

You can then use this custom variable type when creating custom primitives. For example, let's create a primitive that returns a boolean if the age is greater than 100. 
```python
from featuretools.variable_types import Boolean
from featuretools.primitives.base import TransformPrimitive

class AgeOver100(TransformPrimitive):
    name = "age_over_100"
    input_types = [Age]
    return_type = Boolean

    def get_function(self):
        def age_over_100(x, time=None):
            return x > 100
        return age_over_100
```

**Comment by rohan-gt** [comment]
Ah, awesome. An entry in the documentation for the same would be useful.

**Comment by kmax12** [comment]
> Ah, awesome. An entry in the documentation for the same would be useful.

I agree. We can add something to this page: https://docs.featuretools.com/en/stable/variables.html
