### ISSUE TITLE
Test featuretools compatibility with Pandas 1.1.0rc0

### ISSUE THREAD

**Issue by rwedge** [FeatureLabs/featuretools#1072]
New Pandas release candidate.  Not up on PyPI at time of writing but we should run our unit tests using the release candidate when it becomes available.

**Comment by thehomebrewnerd** [comment]
There is currently an issue that is causing Dask unit tests to fail on CircleCI when using `pandas 1.1.0`. The issue has been reported to Dask and is being tracked [here](https://github.com/dask/dask/issues/6454).
