### ISSUE TITLE
Test Koalas on home credit and instacart datasets

### ISSUE THREAD

**Issue by frances-h** [FeatureLabs/featuretools#1127]

**Comment by thehomebrewnerd** [comment]
Aug 28:
Initial runs on both datasets were completed successfully. Time in seconds for each step is shown in the attached images.
![image](https://user-images.githubusercontent.com/4307001/91601029-940f0080-e92e-11ea-81bf-0036b3579fe0.png)

![image](https://user-images.githubusercontent.com/4307001/91601074-a5580d00-e92e-11ea-9959-8ee5bdb3a0a1.png)
