### ISSUE TITLE
How to only generate specific features?

### ISSUE THREAD

**Issue by zhenlingcn** [FeatureLabs/featuretools#1135]
In my case, the amount of experimental data is huge. Thus, I need to use a small set to try different features and then select a subset of features. However, I cannot find an elegant way to only generate those features on the new dataset. How can I implement this function?

**Comment by dlutleixin** [comment]
you can combine your tables into only one big table by using join relations, and generate features by set max_depth=1 in ft.dfs and only set trans_primitives without agg_primitives.

**Comment by rwedge** [comment]
@zhenlingcn when you calculate the features on the smaller dataset, you should get back both a feature matrix and a list of features objects.  If you trim down that feature list to just the subset you want to use on the larger dataset, you can calculate that list of features directly on the large dataset using the `calculate_feature_matrix` function.  This assumes the datasets have the same relationship structure, just a difference in the amount of data.  For convenience, you can use `ft.save_features` and `ft.load_features` to save the feature list you want to use to disk so you can load it in later.

**Comment by rwedge** [comment]
I hope I answered your question, am closing this issue for now.  Feel free to re-open and comment more if this doesn't seem resolved.
