### ISSUE TITLE
Duplicate Label column on approximate cutoff times

### ISSUE THREAD

**Issue by tuethan1999** [FeatureLabs/featuretools#1146]
#### Bug Description
When passing in a cutoff time df that includes the labels, `calculate_feature_matrix` produces two label columns with the suffix of _x and _y

This merge is where the bug is produced:
https://github.com/FeatureLabs/featuretools/blob/58ef9c1d4cfd21f47151d3393ed5f3c551a8a513/featuretools/computational_backends/calculate_feature_matrix.py#L441

#### Expected Output

I believe the desired behavior is to only produce only one label column

#### Reproducability
entityset: 
https://alteryx0-my.sharepoint.com/:f:/g/personal/ethan_tu_alteryx_com/Euy-8yAwLSVIs7_shfKJDmoBAAboCMwrRqrG9GZZJ8qcww?e=pAy4ht

feature list:
https://alteryx0-my.sharepoint.com/:u:/g/personal/ethan_tu_alteryx_com/EU1SlMF0PapHnlSP7W9zZfIB0y9as5Z-N0ZxIdcDwrfVaA?e=e2DwyP

```
import featuretools as ft

es = ft.entityset.read_entityset('geometry_entityset')
cutoff_times = es['transactions'].df[['Transaction Id', 'End Time', 'Outcome']]
cutoff_times.rename(columns={'End Time':'Time'}, inplace=True)

features = ft.load_features('geometry_features')

cfm_kwargs = {
'approximate': '2m',
'cutoff_time': cutoff_times,
'entityset': es,
'features': features
}

 fm = ft.calculate_feature_matrix(**cfm_kwargs)
```

#### Output of ``featuretools.show_info()``

Featuretools version: 0.18.1
Featuretools installation directory: /home/ec2-user/.pyenv/versions/3.8.2/envs/venv/lib/python3.8/site-packages/featuretools

SYSTEM INFO
-----------
python: 3.8.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.186-146.268.amzn2.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.19.1
pandas: 1.1.0
tqdm: 4.48.2
PyYAML: 5.3.1
cloudpickle: 1.5.0
dask: 2.23.0
distributed: 2.23.0
psutil: 5.7.2
pip: 19.2.3
setuptools: 41.2.0

**Comment by rwedge** [comment]
Do you have a code example where this occurs?

**Comment by rwedge** [comment]
Great, I was able to reproduce.  Looks like the issue is that if a extra column in the cutoff time dataframe matches the name of a feature, we're avoiding the collision by adding the `_x` and `_y` suffixes without mentioning this to the user

**Comment by tuethan1999** [comment]
In pr #1147, I've made the expected behavior to ignore the column with the same name in the cutoff times. However, it seems like the expected behavior should just be a warning saying that we're going to add _x and _y suffixes?
