### ISSUE TITLE
when to use ”es.normalize_entity“

### ISSUE THREAD

**Issue by Jie-Yuan** [FeatureLabs/featuretools#1154]
when to use ”es.normalize_entity“

Feel very hard to use "featuretools"

**Comment by rwedge** [comment]
Hi @Jie-Yuan 

Normalize entity can be used to split out some fields in an entity to a separate entity.  [This section](https://docs.featuretools.com/en/stable/loading_data/using_entitysets.html#creating-entity-from-existing-table) of the docs goes into more detail.

I'll close this issue for now but feel free to respond / re-open if you need more clarification!
