### ISSUE TITLE
Does a single thread need less memory?

### ISSUE THREAD

**Issue by Jie-Yuan** [FeatureLabs/featuretools#1158]
~/anaconda3/lib/python3.7/site-packages/featuretools/computational_backends/utils.py in create_client_and_cluster(n_jobs, dask_kwargs, entityset_size)
    187         worker_limit = worker['memory_limit']
    188         if worker_limit < entityset_size:
--> 189             raise ValueError("Insufficient memory to use this many workers")
    190         elif worker_limit < 2 * entityset_size and not warned_of_memory:
    191             logger.warning("Worker memory is between 1 to 2 times the memory"

ValueError: Insufficient memory to use this many workers

**Comment by rwedge** [comment]
@Jie-Yuan yes, a single thread needs less memory.  When using n_jobs parameter, more jobs means less memory per worker.

**Comment by kmax12** [comment]
@Jie-Yuan you may want to try our [Dask](https://featuretools.alteryx.com/en/stable/guides/using_dask_entitysets.html) or [koalas](https://featuretools.alteryx.com/en/stable/guides/using_dask_entitysets.html) integrations for running on multiple cores.
