### ISSUE TITLE
Feature definitions not compatible between v0.3.0 and newer versions.

### ISSUE THREAD

**Issue by WillKoehrsen** [FeatureLabs/featuretools#311]
This might be a known issue already, but I have a set of features created in Featuretools v0.3.0 that do not work when I use `ft.load_features` in v0.3.1. I have uploaded the set of feature definitions. 

The following code works fine in v0.3.0 but not in v0.3.1:

`f = ft.load_features('features-2')`

The error is : `TypeError: 'str' object does not support item assignment`. I can post a full stack trace if necessary. 

[features-defs.zip](https://github.com/Featuretools/featuretools/files/2568401/features-defs.zip)

**Comment by WillKoehrsen** [comment]
The features also do not load in v0.4.0.

**Comment by kmax12** [comment]
Features saved in one version of Featuretools may not be able to be loaded in another version of Featuretools due to our usage pickle.

We should add this to the documentation for `ft.save_features` and `ft.load_features` as well as the deployment page.

Open issue #315 to fix this.

**Comment by WillKoehrsen** [comment]
#316 helps on this issue by alerting users to incompatibility, however, do we want to try and make features compatible between versions? At the very least, the warning when users try to load in features from a different version should mention the incompatibility. Currently, the error is not very useful.

**Comment by rwedge** [comment]
I think the serialization changes and use of schema versioning added since the issue was opened have addressed the problem.
