### ISSUE TITLE
Increasing max_features performance

### ISSUE THREAD

**Issue by ugurcanlacin** [FeatureLabs/featuretools#327]
I realized that setting max_features parameter does not change the running time, which I would expect it faster since we directly say the maximum number of features. I checked the code and saw that we return the number of features after calculated the total number of features. 

In this case, I think `new_features` should be calculated according to max_features parameters, so we do not have to wait for the entire calculation.

https://github.com/Featuretools/featuretools/blob/68db36108a5deffaaed267668d5ac90291ec2b84/featuretools/synthesis/deep_feature_synthesis.py#L269

**Comment by kmax12** [comment]
You are right that we still generate all the feature definitions. However, setting `max_features` will reduce the number of feature definitions returned by DFS resulting in fewer actual feature calculations to happen. The bottleneck is usually the calculation of the actual feature values, not the feature definitions, so this a helpful parameter to decrease overall runtime.

**Comment by rwedge** [comment]
Closing this for now.  If anyone is able to share a specific use case where the slowdown is significant, we'd love to look into it more.
