### ISSUE TITLE
Option for `calculate_feature_matrix` to fail quietly

### ISSUE THREAD

**Issue by chappers** [FeatureLabs/featuretools#36]
Is it possible to have `calculate_feature_matrix` to fail quietly? I'm thinking something similar to how many R functions have `na.option=pass`. The reason for this is when you are scoring on new data, say for production and you have some weird data in it, you may want a warning to come up, but you don't want the whole process to stop.

Basically if it were to error out, instead it will fill in the column with `na` and continue on.

**Comment by kmax12** [comment]
That is an interesting suggestion and could definitely help production deployment. I would be a bit concern about silencing legitimate errors, but I an option could be useful. For existing deployments, we do validation outside of the `calculate_feature_matrix` call.

Similar to your suggestion, we could accomplish this with an  `error` parameter that could be `raise` (the default) or  `ignore`.  If `raise`, raise the exception and if `coerce`, set as NaN. This would be naming conventions I've seen for this scenario in Pandas. Given this is would be a non-breaking API change, we could make this work. 

@chappers what are you thoughts on the proposal above?

**Comment by chappers** [comment]
@kmax12 that proposal sounds sensible! Thanks

**Comment by kmax12** [comment]
Closing this issue for now since it's been open for a while and there doesn't seem to be strong need for this. If anyone comes across this and can share more info about their use case, feel free to comment and reopen.
