### ISSUE TITLE
 support for high-dimensional sparse data ?

### ISSUE THREAD

**Issue by yangzhg** [FeatureLabs/featuretools#392]
Does featuretools support  high-dimensional sparse data?  how to use dfs  on high-dimensional sparse data

**Comment by kmax12** [comment]
Featuretools relies on pandas dataframes for data storage. We support what they support.

Can you provide an example of a type of feature engineering youd like to do an specific spare dataset? Than I might be able to suggest how Featuretools can help.

**Comment by yangzhg** [comment]
Our data is stored in libsvm or csr/csc format. When converted to pandas dataframe, it will become extremely large.

**Comment by yangzhg** [comment]
> Featuretools relies on pandas dataframes for data storage. We support what they support.
> 
> Can you provide an example of feature engineering you'd like to do an specific sparse dataset? Than I might be able to suggest how Featuretools can help.

Our data is stored in libsvm or csr/csc format. When converted to pandas dataframe, it will become extremely large.

**Comment by Claire-jyw** [comment]
yes, same here! We have libsvm/csr format data with over 150k features. How could we utilize DFS to handle this type of data in order to reduce the high dimension (feature selection) and then feature transformation? Thanks

**Comment by rwedge** [comment]
Closing for now, open discussing more given more specific on use case
