### ISSUE TITLE
Create a page in docs of available primitives based on sources

### ISSUE THREAD

**Issue by grayskripko** [FeatureLabs/featuretools#449]
Each file [in this folder](https://github.com/Featuretools/featuretools/tree/master/featuretools/primitives/standard) is a name of group. Each class inside a file contains description and can be used in [the table](https://docs.featuretools.com/api_reference.html#cumulative-transform-primitives)

**Comment by kmax12** [comment]
you can find documentation of all primitives available here: https://primitives.featurelabs.com/

**Comment by grayskripko** [comment]
wow, great!
