### ISSUE TITLE
Drop Python 2.7 Support

### ISSUE THREAD

**Issue by kmax12** [FeatureLabs/featuretools#451]
The Python core team plans to stop supporting Python 2 in 2020. Many of Featuretools dependencies have already stated they will no longer be making releases that support python 2.7 or have already dropped Python 2.7 support. For example

* Numpy: January 1, 2019 ([details](https://docs.scipy.org/doc/numpy-1.14.1/neps/dropping-python2.7-proposal.html))
* Pandas: January 1, 2019 ([details](https://pandas.pydata.org/pandas-docs/version/0.23.4/install.html#install-dropping-27))
* Scikit Learn: version 0.21 ([details](https://scikit-learn.org/stable/whats_new.html#version-0-20-0))

As of now, Featuretools does not have a date or a version we plan to drop Python 2.7, but this issue is meant to serve as a notice that it is coming in the near future. Please comment here with any comments or questions.

Thanks!

**Comment by jeff-hernandez** [comment]
Projects with date or version on dropping support for Python 2.7:
- Python: January 1, 2020 ([details](https://devguide.python.org/#status-of-python-branches))
- Numpy: January 1, 2019 ([details](https://docs.scipy.org/doc/numpy-1.14.1/neps/dropping-python2.7-proposal.html))
- Pandas: January 1, 2019 ([details](https://pandas.pydata.org/pandas-docs/version/0.23.4/install.html#install-dropping-27))
- Pytest: version 5.0 ([details](https://github.com/pytest-dev/pytest/blob/6154a5ac0241f258083053ca62d39695743013c3/doc/en/py27-py34-deprecation.rst#python-27-and-34-support-plan))
- Sphinx: version 2.0.0, (will also drop support for Python 3.4) ([details](https://github.com/sphinx-doc/sphinx/blob/97d99f830258a4612a6c77f5be084819634dcbad/CHANGES#L31))
- Scikit Learn: version 0.21, (will also drop support for Python 3.4) ([details](https://scikit-learn.org/stable/whats_new.html#version-0-20-0))
- Scikit Image: version 0.14.1 ([details](http://scikit-image.org/docs/dev/release_notes_and_installation.html#announcement-scikit-image-0-14-1))
- IPython: version 6.0 ([details](https://blog.jupyter.org/release-of-ipython-5-0-8ce60b8d2e8e))
- Matplotlib: version 3.0 ([details](https://github.com/matplotlib/matplotlib/issues/9404/#issue-265527337))
- Bokeh: TBA ([details](https://github.com/bokeh/bokeh/wiki/BEP-5:-Python-2-Support-Timeline))
- Tornado: version 6.0 ([details](http://www.tornadoweb.org/en/stable/#installation))
- Django: version 2.0 ([details](https://docs.djangoproject.com/en/2.1/faq/install/#what-python-version-should-i-use-with-django))
- Celery: version 5.0 ([details](http://docs.celeryproject.org/en/latest/getting-started/introduction.html#what-do-i-need))
- SymPy: January 1, 2020 ([details](https://github.com/sympy/sympy/wiki/Python-version-support-policy))
- Numba: January 1, 2019 ([details](https://numba.pydata.org/numba-doc/dev/reference/python27-eol.html))
- Kivy: January 1, 2019 ([details](https://github.com/kivy/kivy/wiki/Kivy-Python-2-Support-Timeline))
- Buildbot: February 2019 ([details](https://github.com/buildbot/buildbot/issues/4439#issue-381854116))
- PyMC3: version 3.7 ([details](https://github.com/pymc-devs/pymc3/blob/master/RELEASE-NOTES.md#pymc3-36-dec-21-2018))
- GeoPy: version 2.0 ([details](https://geopy.readthedocs.io/en/stable/#geopy-2-0))
- Xarray, version 0.11.1 ([details](http://xarray.pydata.org/en/stable/whats-new.html?highlight=drop%20support%20python%202#v0-11-0-7-november-2018))
- CherryPy: version 18.0.0 ([details](http://docs.cherrypy.org/en/latest/))
- music21: version 5 ([details](https://music21-mit.blogspot.com/2018/03/music21-v5-released.html))

**Comment by jeff-hernandez** [comment]
This tables shows the version usage and installations of `featuretools` for February 2019.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.5            |  77.61% |         24,328 |
| 2.7            |  10.15% |          3,182 |
| 3.6            |   9.83% |          3,082 |
| 3.7            |   2.15% |            675 |
| 3.4            |   0.24% |             76 |
| 3.8            |   0.01% |              2 |
| Total          |         |         31,345 |

**Comment by kmax12** [comment]
This was done in #759 and released in Featuretools 0.12.0
