### ISSUE TITLE
dfs(n_jobs > 1) warning "Event loop was unresponsive in Nanny"

### ISSUE THREAD

**Issue by grayskripko** [FeatureLabs/featuretools#473]
The full message
```distributed.core - INFO - Event loop was unresponsive in Nanny for 91.74s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.```
repeats many times after dfs() execution.

I have a guess that I need to stop Cluster manually taking into account the fact that I use ```featuretoolsR``` wrapper and this could cause some problems.

Is there a way how to get a started Cluster in order to try to stop it?
Should I pass something special to `dask_kwargs`?

**Comment by rwedge** [comment]
Hey @grayskripko , sorry about the late response.  Were you able to get more inight into this warning?

You can calculate features with an already started dask cluster by providing a `dask_kwargs` dictionary that has a 'cluster' entry in it.  The cluster entry should either be a reference to the cluster you started or a string with the address / ports of the cluster.

We are working on an alternate parallelization approach using Dask Dataframes, see #783

**Comment by grayskripko** [comment]
I don't remember. You can keep this issue as a reminder or close it
