### ISSUE TITLE
Docs should show how to create custom primitives that operate on columns satisfying a predicate

### ISSUE THREAD

**Issue by Julian** [FeatureLabs/featuretools#540]
### Bug/Feature Request Description

Will update this if I figure out how to actually do it, but as a new user reading the docs on 
how to implement custom primitives, it's a bit hard to figure out how to create new custom primitives that operate on only a subset of their input types' valid values.

I.e., if I have columns that represent URLs, I want to define a custom transform that operates on strings, but only strings that are URLs, and then return their composite parts individually.

Separately, the second part of that isn't easy to tell how to do either -- all the examples simply return a scalar value rather than wanting to explode into multiple values.

I can *guess* that the solution to 1 is maybe to define a new (algebraic) input type as a subset of `Text` (which also doesn't seem documented -- how to define new types), or possibly to just have the function I pass in not return anything if the input isn't one of the column types it cares about?

And maybe to the second part there seems to be a slightly convoluted example of something similar in the [api docs](https://docs.featuretools.com/generated/featuretools.primitives.make_trans_primitive.html#featuretools.primitives.make_trans_primitive) where it looks like possibly you end up with some indirection, but if that's the current way to do it, maybe it'd be easier to be able to just have an API somewhat like:

```
@featuretools.primitives.explode
def str_to_url(column_name, value):
    parsed_url = some_library.from_text(value)
    return {column_name + ".". + key: value for key, value in parsed_url.asdict()}
```

Apologies if anything I've said is non-sensical given I'm only about an hour into the library, but figured it might be helpful to mention, since it's the first wall hit when starting out for me.

**Comment by CJStadler** [comment]
Both parts of this are possible, but I definitely agree that they are not well documented.

1. For your specific example of URLs, there is already a `URL` type defined in featuretools (all types are listed [here](https://docs.featuretools.com/api_reference.html#variable-types)). More generally, although this is not explicitly supported, you can define new variable types by subclassing an existing type:

```py
import featuretools as ft

class MyURL(ft.variable_types.Variable):
    type_string = "url"
    _default_pandas_dtype = str
```

Then, when you create an entity you can use this class in `variable_types`: https://docs.featuretools.com/loading_data/using_entitysets.html#adding-entities

2. To output multiple columns set `number_output_features` for your primitive. The primitive function will also need to return the correct number of values, and you will need a function to return the names for each column:

```py
COMPONENTS = ['scheme', 'host', 'path']

def extract_components(urls):
    parsed = some_library.from_text(urls)
    return [parsed[component] for component in COMPONENTS]

def component_names(primitive):
    base_feature = primitive.base_features[0].get_name()
    return ['%s(%s)' % (component, base_feature) for component in COMPONENTS]

URLComponents = ft.primitives.make_trans_primitive(
    extract_components,
    input_types=[MyURL],
    return_type=ft.variable_types.Text,
    number_output_features=len(COMPONENTS),
    cls_attributes={'get_feature_names': component_names}
)

# Or, write the primitive as a class
class URLComponents(ft.primitives.TransformPrimitive):
    name = "url_components"
    input_types = [MyURL]
    return_type = ft.variable_types.Text
    number_output_features = len(COMPONENTS)

    def get_function(self):
        return extract_components

    def get_feature_names(self):
        return component_names(self)
```

**Comment by Julian** [comment]
Thanks! Very helpful -- and glad to hear I guess I was on the right track then.

Just on the last example there where `return_type` looks like it's just one type -- does that mean then that the return type, if it's multiple columns, has to be homogeneous? I.e. (for some hypothetical other example) you can't return multiple exploded columns and have some of them text and some numbers?

**Comment by CJStadler** [comment]
Yes, currently there is no way to specify multiple return types.

**Comment by Julian** [comment]
Great, thanks! Is it worth leaving this open, or if I happen to get a chance to transfer your examples into them should I just send a PR?

**Comment by CJStadler** [comment]
Since the docs should be updated I think we can leave this open. If you want to submit a PR that would be great!

**Comment by Julian** [comment]
Following up here on one other similar point (and hopefully not sounding like usage advice at this point :), if so happy to take this to a different channel), but another thing that's a bit hard to figure out at the minute even with the pages you've linked is what type to use for containers -- e.g., if the data type is "list of URLs", in the above example, I don't see how to specify compound input types yet.

**Comment by kmax12** [comment]
we've documented how to define features with multiple outputs [here](https://docs.featuretools.com/en/stable/guides/advanced_custom_primitives.html#features-with-multiple-outputs), so going to close this for now. 

if there is something that is still missing in the latest version of the docs or featuretools, please feel free to reopen a new issue!

**Comment by Julian** [comment]
Awesome, will look there! Thanks again for the help along the way.
