### ISSUE TITLE
Better test case for normalizing from no time index to time index

### ISSUE THREAD

**Issue by gsheni** [FeatureLabs/featuretools#554]
The test case here:
https://github.com/Featuretools/featuretools/blob/master/featuretools/tests/entityset_tests/test_es.py#L829
Needs to improved to better and more realistic test normalizing with no time index, and verify that a new time index was created.

**Comment by rwedge** [comment]
Looks like the line number has shifted over time, but I think the general idea here is that this test could be improved:

```python
def test_normalize_time_index_from_none(es):
    es['customers'].time_index = None
    es.normalize_entity('customers', 'birthdays', 'age',
                        make_time_index='date_of_birth',
                        copy_variables=['date_of_birth'])
    assert es['birthdays'].time_index == 'date_of_birth'
    assert es['birthdays'].df['date_of_birth'].is_monotonic_increasing
```
Instead of taking an existing entity that already has a time index and removing it, we could change the test so it the entity never had a time index
