### ISSUE TITLE
Primitive Function redundant casting 

### ISSUE THREAD

**Issue by ctduffy** [FeatureLabs/featuretools#562]
The primitive functions in transform_primitives take in a pandas series as an input, so inside these primitives it is no longer necessary to cast the input to a Series.

**Comment by Raul9595** [comment]
Can I work on this issue ?

**Comment by kmax12** [comment]
@Raul9595 sure! just put up a PR once you are ready for us to revie

**Comment by kmax12** [comment]
@Raul9595 are you still planning to work on this issue?

**Comment by rwedge** [comment]
Many of these castings will be removed by #783
