### ISSUE TITLE
dfs doesn't use TimeSince primitives on datetime features

### ISSUE THREAD

**Issue by Ingvar-Y** [FeatureLabs/featuretools#604]
### Bug/Feature Request Title

TimeSince primitives don't calculate on Datetime and DateOfBirth features (but calculate on DatetimeTimeIndex). That doesn't seem right since you can have a few columns describing different timestamps you may want to use.

Actually, is there any way to check which primitives apply to which variable_types?

My featuretools package is built from master branch.

#### Output of ``featuretools.show_info()``
BTW show_info() doesn't provide any output so I used `featuretools.utils.cli_utils.print_info()` instead.
<details>
Featuretools version: 0.8.0
Featuretools installation directory: y:\git\featuretools\featuretools

SYSTEM INFO
-----------
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 2008ServerR2
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

INSTALLED VERSIONS
------------------
numpy: 1.16.4
pandas: 0.24.2
tqdm: 4.32.1
toolz: 0.9.0
PyYAML: 5.1.1
cloudpickle: 1.2.1
future: 0.17.1
dask: 1.2.2
distributed: 1.28.1
psutil: 5.6.3
Click: 7.0
scikit-learn: 0.21.2
pip: 19.1.1
setuptools: 41.0.1
</details>

**Comment by kmax12** [comment]
You're right, `TimeSince` probably should automatically apply to `DateTime` and `DateOfBirth` variables

A workaround for the time being would be to manually define these features as seed features, which you can read more about [here](https://docs.featuretools.com/guides/tuning_dfs.html#using-seed-features).

For example,

```python
import featuretools as ft
from featuretools.primitives import TimeSince

es = ft.demo.load_mock_customer(return_entityset=True)

time_since_dob = ft.Feature(es["customers"]["date_of_birth"], primitive=TimeSince(unit="years"))

fm, fl = ft.dfs(target_entity="customers",
                entityset=es,
                agg_primitives=["count"],
                trans_primitives=[TimeSince(unit="years")],
                seed_features=[time_since_dob])
fm
```

this returns 

```            zip_code  COUNT(sessions)  COUNT(transactions)  TIME_SINCE(date_of_birth, unit=years)  TIME_SINCE(join_date, unit=years)
customer_id                                                                                                                         
1              60091                8                  126                              24.934902                           8.176889
2              13244                7                   93                              32.854445                           7.178305
3              13244                6                   93                              15.585403                           7.853083
4              60091                8                  109                              12.851503                           8.200479
5              60091                6                   79                              34.911719                           8.928089```
```

Note: make sure to pull the latest master before running the example above

**Comment by philipus** [comment]
which cut off time will be used when doing so? When you have different cut off times like for rolling data sets in time series problems what can you do in this case?!

**Comment by kmax12** [comment]
it will use the cutoff time supplied to either `ft.calculate_feature_matrix` or `ft.dfs`. If you have different cutoff times you need provide a dataframe to the `cutoff_time` parameter as described [here](https://docs.featuretools.com/automated_feature_engineering/handling_time.html#using-a-cutoff-time-dataframe).

**Comment by kmax12** [comment]
Per my discussion with @rwedge, let's solve this by creating an `Age` primitive that applies to date of birth. We should also make this a default primitive
