### ISSUE TITLE
TSFresh

### ISSUE THREAD

**Issue by firmai** [FeatureLabs/featuretools#662]
Is all of TSFresh absorbed into your product? I am particularly looking at this documentation. If it is not, are there plans to do that? If there are not plans, is there any comparative study you know about? How many more function and function varieties do you have in your package? 

https://docs.featuretools.com/getting_started/install.html

**Comment by kmax12** [comment]
@firmai We've built an integration of the TSFresh feature calculators as [primitives](https://docs.featuretools.com/automated_feature_engineering/primitives.html) in Featuretools, not the whole TSFresh API, so I wouldn't say we've "absorbed it". 

The TSFresh primitives we've integrated will be applied using our Deep Feature Synthesis algorithm and combined with our existing set 50+ primitives, so you may get slightly different results. However, you should be able to calculate everything you could in TSFresh in Featuretools in some way or another. 

There's no comparative study that I know of. The libraries have slightly different goals, so it may not be an apples-to-apples comparison. Featuretools aims to be more general and work with time series and relational data with a particular focus on [how selecting data by time is handled](https://docs.featuretools.com/automated_feature_engineering/handling_time.html). TSFresh focuses on time series specifically and contains more feature selection capabilities at this point in time. I am not personally expert on TSFresh nor should I speak on their behalf, so you could speak to the authors of that library for additional perspective as well.

**Comment by firmai** [comment]
That is excellent, thanks for the explanation.
