### ISSUE TITLE
only one data table???

### ISSUE THREAD

**Issue by Jie-Yuan** [FeatureLabs/featuretools#684]
If I only have one table, I want to use the category as an index.

**Comment by kmax12** [comment]
hi @Jie-Yuan, take a look at[ this FAQ answer](https://docs.featuretools.com/frequently_asked_questions.html#How-do-I-apply-DFS-to-a-single-table?). 

If it doesn't help, please share your dataset and a specific example of what you are trying to do so we can better help.
