### ISSUE TITLE
Feature Lists Have Different Ordering In Python 3.5 vs. 3.6+

### ISSUE THREAD

**Issue by jeremyliweishih** [FeatureLabs/featuretools#687]
### Feature Lists Have Different Ordering In Python 3.5 vs. 3.6+
Due to dictionaries retaining insertion order in python 3.6+, feature lists in Python 3.6 and 3.6+ have a different order. It is unknown where this creates issues other than serialization and deserializing between different versions

**Comment by rwedge** [comment]
Since Featuretools has dropped Python 3.5, we no longer have this problem
