### ISSUE TITLE
how to create custom aggregation primitive function of a list type using custom variable types

### ISSUE THREAD

**Issue by heemokyim** [FeatureLabs/featuretools#711]
I have two questions about featuretools's make_agg_primitives function and make_trans_primitives.

In my data there are values that consist of list format.

I want to aggregate the products columns by using various custom functions:

For example,

-my trial-

first question

    input data
    
    id products
    1 [a, b, c, a]
    1 [a, c, c, a]
    2 [a, c, c, a]
    2 [c,c,c,c,c,c]
    
    output data1 
    
    id products
    1 [a, b, c, a, a, c, c, a]
    2 [a,c,c,a,c,c,c,c,c,c]

my code about the first question

    def sum_list(values):
    return sum(values,[])

    
    max_frequent_list= make_agg_primitive(function = sum_list,
                                      input_types = [List],
                                      return_type = List,
                                      description="sum of a list related instance")

##########################################################

second question

    input data
    
    id products
    1 [a, b, c, a, c, c, a]
    2 [a, c, c, a,c,c,c,c,c,c]
    
    output data
    id product
    1 a
    2 c

my code about the second question

    def max_frequent_list(values):
        def most_common(l):
            try:
                return mode(l)
            except StatisticsError as e:
                # will only return the first element if no unique mode found
                if 'no unique mode' in e.args[0]:
                    return random.choice(l)
                # this is for "StatisticsError: no mode for empty data"
                # after calling mode([])
                raise
        return values.apply(lambda x: most_common(x))
    
    max_frequent_list= make_trans_primitive(function = max_frequent_list,
                                      input_types = [List],
                                      return_type = String,
                                      description="common value of a list related instance")

**Comment by kmax12** [comment]
@heemokyim thank you for posting, we'd be happy to help.

what is the specific question/issue you're facing?

**Comment by rwedge** [comment]
Closing this issue for now since it's gone stale.  @heemokyim if you still would like help with these issues feel free to re-open the issue and let us know where you need help!
