### ISSUE TITLE
Allow DFS to take in pd.DateOffset objects

### ISSUE THREAD

**Issue by jeremyliweishih** [FeatureLabs/featuretools#729]
Currently DFS and TimeDelta does not take in pd.DateOffset objects. This could require more refactoring with our TimeDelta class. Certain areas to take into consideration:

- [ ] `training_window` must support this new functionality 
- [ ] `use_previous` must support this new functionality. Take into account that we need to be able to serialize features.

**Comment by rwedge** [comment]
Addressed by #732
