### ISSUE TITLE
Replace `path_management` fixture with `pytest.tmpdir` fixture

### ISSUE THREAD

**Issue by jeremyliweishih** [FeatureLabs/featuretools#761]
#### Bug/Feature Request Description:

Currently we define a custom fixture to clean up our serialization tests in `entityset_tests.test_serialization`. We can replace our custom fixture with pytest's tmpdir.

http://doc.pytest.org/en/latest/tmpdir.html

**Comment by rwedge** [comment]
Fixed in #811
