### ISSUE TITLE
Slack links in help.rst, contributing.md and README.md are inactive

### ISSUE THREAD

**Issue by gr33n-made** [FeatureLabs/featuretools#762]
### Slack link in documentation are inactive. 
Slack links in documentation are inactive.
They don't work and links to 'This invite link is no longer active.' page.
Site links are out of date too.

**Comment by kmax12** [comment]
Thanks for heads up! Working on it here #765 

In the meantime, new link is: https://join.slack.com/t/featuretools/shared_invite/enQtNTEwODEzOTEwMjg4LTQ1MjZlOWFmZDk2YzAwMjEzNTkwZTZkN2NmOGFjOGI4YzE5OGMyMGM5NGIxNTE4NjkzYWI3OWEwZjkyZGExYmQ
