### ISSUE TITLE
Cutoff time & training_window & dfs bug?

### ISSUE THREAD

**Issue by rightx2** [FeatureLabs/featuretools#766]
### Bug/Feature Request Title
Cutoff time & `dfs` bug

 
#### Bug/Feature Request Description

1. code
```
data_df = pd.DataFrame(
    {
        "store_id": [0,0,0,1,1,1],
        "region": ["A", "A", "A", "B", "B", "B"],
        "amount": [1,2,3,4,5,6],
        "transacted_datetime": [
            '2012-01-01 04:00', '2012-01-02 04:00', '2012-04-01 04:00',
            '2012-04-02 04:00', '2012-07-02 04:00', '2012-07-03 04:00',
        ]
    }
)
data_df['transacted_datetime'] = pd.to_datetime(data_df['transacted_datetime'])

fake_y_df = pd.DataFrame(
    {
        "store_id": [0, 1, 0, 1],
        "cutoff_time": ["2012-04-01", "2012-04-01", "2012-07-01", "2012-07-01",],
        "3month_amount_sum_from_cutoff_time": [3, 4, 0, 11]
    }
)
fake_y_df['cutoff_time'] = pd.to_datetime(fake_y_df['cutoff_time'])


import featuretools as ft
es = ft.EntitySet(id="sale_set") 
es = es.entity_from_dataframe(
    "sales",
    dataframe=data_df, 
    index="sale_id", make_index=True,
    time_index='transacted_datetime',
)
es.normalize_entity(
    new_entity_id="stores", 
    base_entity_id="sales", 
    index="store_id", 
    additional_variables=['region']
)

features  = ft.dfs(
    entityset=es,
    target_entity='stores',
    cutoff_time = fake_y_df,
    verbose = 1,
    cutoff_time_in_index = True,
    n_jobs = -1,
    max_depth = 2,
    agg_primitives=["sum", "std", "max"],
    trans_primitives=None, 
    training_window="3 month", 
)

```
And result matrix has something wrong in it.
![Screen Shot 2019-10-05 at 11 50 08](https://user-images.githubusercontent.com/10606994/66248821-50d00000-e766-11e9-907f-fd7a04416eec.png)

#### Expected Output
![Screen Shot 2019-10-05 at 11 50 43](https://user-images.githubusercontent.com/10606994/66248844-94c30500-e766-11e9-8ea9-07f2a467e6f1.png)

#### Output
Below is a screenshot of `features[0]` (Result matrix)
![Screen Shot 2019-10-05 at 11 52 27](https://user-images.githubusercontent.com/10606994/66248847-a1475d80-e766-11e9-9c18-ab5a03bfeb9f.png)

<details>
I think that this is problem related with `cutoff_time` and `training_window`

What I was meant to do:
Let say `training_window="3 months"` . Then,
1. if `cutoff_time` = 2019-04-01 -> `SUM(sales_amount)` should be sum of amount in "2019-01-01 00:00:01~ 2019-03-31 23:59:59" 
2. if `cutoff_time` = 2019-07-01 -> `SUM(sales_amount)` should be sum of amount in "2019-04-01 00:00:01 ~ 2019-06-30 23:59:59" 

But as you can see the images, `store_id=0` and `cutoff_time=2012-07-01`'s `SUM(sales.amount)` is 0, which means it didn't count `2012-04-01 04:00:00` transaction of store 0......
I had changed `cutoff_time` to end of month(e.g. 2019-03-31, 2019-06-30) as well, but similar problem occured again....

Plus, `region` field. Why does it fill it with `nan`?...

Did I miss something?

</details>

**Comment by rwedge** [comment]
Hi @rightx2 , 

When using a training window, it is necessary to calculate the [last time indexes](https://docs.featuretools.com/automated_feature_engineering/handling_time.html?highlight=last_time_index#setting-a-last-time-index) for the entity set.  Adding

```python
es.add_last_time_indexes()
```

to the end of the entityset creation code so it looks like this

```python
es = ft.EntitySet(id="sale_set") 
es = es.entity_from_dataframe(
    "sales",
    dataframe=data_df, 
    index="sale_id", make_index=True,
    time_index='transacted_datetime',
)
es.normalize_entity(
    new_entity_id="stores", 
    base_entity_id="sales", 
    index="store_id", 
    additional_variables=['region'],
)
es.add_last_time_indexes()
```
Resulted in the dfs call returning the `SUM(sales_amount)` values you were expecting

Since `last_time_index` isn't always necessary for feature calculations and can take some time to run it is not calculated by default.

For the `region` is `nan` issue, that is because of how the stores entity is set up

```python
es.normalize_entity(
    new_entity_id="stores", 
    base_entity_id="sales", 
    index="store_id", 
    additional_variables=['region'],
)
```

Since the sales entity has a time index ("transacted_datetime"), ``normalize_entity`` will automatically create a time index for the stores entity based on the first sale for each store.  Since Featuretools thinks the store begins to exist at the time of its first recorded sale (2012-4-2), it doesn't think the store exists at 2012-4-1 and returns `nan` because there is no data for the store at that time.  Explicitly saying not to add a time index to the stores entity is one way to fix this problem.

```python
es.normalize_entity(
    new_entity_id="stores", 
    base_entity_id="sales", 
    index="store_id", 
    additional_variables=['region'], 
    make_time_index=False
)
```

**Comment by rightx2** [comment]
@rwedge  Last solution you said, `not to add a time index`, If I do that and run `dfs`, it shows warning: `Using training_window but last_time_index is not set on entity sales`...

**Comment by rwedge** [comment]
@rightx2  did you also call `es.add_last_time_indexes()`?

I do not encounter a warning when I run this code:

```python
import featuretools as ft
import pandas as pd

data_df = pd.DataFrame(
    {
        "store_id": [0,0,0,1,1,1],
        "region": ["A", "A", "A", "B", "B", "B"],
        "amount": [1,2,3,4,5,6],
        "transacted_datetime": [
            '2012-01-01 04:00', '2012-01-02 04:00', '2012-04-01 04:00',
            '2012-04-02 04:00', '2012-07-02 04:00', '2012-07-03 04:00',
        ]
    }
)
data_df['transacted_datetime'] = pd.to_datetime(data_df['transacted_datetime'])

fake_y_df = pd.DataFrame(
    {
        "store_id": [0, 1, 0, 1],
        "cutoff_time": ["2012-04-01", "2012-04-01", "2012-07-01", "2012-07-01",],
        "3month_amount_sum_from_cutoff_time": [3, 4, 0, 11]
    }
)
fake_y_df['cutoff_time'] = pd.to_datetime(fake_y_df['cutoff_time'])


es = ft.EntitySet(id="sale_set") 
es = es.entity_from_dataframe(
    "sales",
    dataframe=data_df, 
    index="sale_id",
    make_index=True,
    time_index='transacted_datetime',
)
es.normalize_entity(
    new_entity_id="stores", 
    base_entity_id="sales", 
    index="store_id", 
    additional_variables=['region'], 
    make_time_index=False
)
es.add_last_time_indexes()

features  = ft.dfs(
    entityset=es,
    target_entity='stores',
    cutoff_time = fake_y_df,
    verbose = 1,
    cutoff_time_in_index = True,
    max_depth = 2,
    agg_primitives=["sum", "std", "max"],
    trans_primitives=None, 
    training_window="3 month", 
)
```

**Comment by rwedge** [comment]
@rightx2 is this issue good to close?

**Comment by rightx2** [comment]
@rwedge Absolutely
