### ISSUE TITLE
Automated feature engineering has not increased in accuracy, but with manual feature engineering, it is boosted. 

### ISSUE THREAD

**Issue by vackysh** [FeatureLabs/featuretools#769]
Hi Experts,

I have a use case where i implemented automated feature engineering to dataset and it is capable of generating new features, but i couldn't see any changes in model's accuracy after featuretools is implemented.

feature_matrix, feature_names = ft.dfs(entityset=es, 
        target_entity = 'creditloanstatus',                                       
        agg_primitives=["sum","std","max","min",],                                       
        max_depth = 2, 
        verbose = 1)

If i add same features  (SUM,STD,MAX,MIN) manually in database, there is a boost in model's accuracy from 62% to 72%.

I compared both the datasets after implementing manual and automation feature engg and there is no difference.

Could you please let me know the reason why featuretools is not adding any value to the final model ?

Regards,
Vackysh

**Comment by kmax12** [comment]
sorry, for slow reply here and thanks for sharing. are you able to send us a reproducible example that we can run to investigate? 

I'm going to close for now, but feel free to reopen if you can share the reproducible example
