### ISSUE TITLE
TypeError: Object of type 'int64' is not JSON serializable

### ISSUE THREAD

**Issue by RomaKoks** [FeatureLabs/featuretools#784]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-232-e948c25a1cb0> in <module>
----> 1 es.to_parquet('incidents_es_parquet')

~/anaconda3/envs/eq-fault/lib/python3.6/site-packages/featuretools/entityset/entityset.py in to_parquet(self, path, engine, compression, profile_name)
    168                 profile_name (str) : Name of AWS profile to use, False to use an anonymous profile, or None.
    169         '''
--> 170         serialize.write_data_description(self, path, format='parquet', engine=engine, compression=compression, profile_name=profile_name)
    171         return self
    172 

~/anaconda3/envs/eq-fault/lib/python3.6/site-packages/featuretools/entityset/serialize.py in write_data_description(entityset, path, profile_name, **kwargs)
    152                 raise
    153 
--> 154         dump_data_description(entityset, path, **kwargs)
    155 
    156 

~/anaconda3/envs/eq-fault/lib/python3.6/site-packages/featuretools/entityset/serialize.py in dump_data_description(entityset, path, **kwargs)
    162     file = os.path.join(path, 'data_description.json')
    163     with open(file, 'w') as file:
--> 164         json.dump(description, file)
    165 
    166 

~/anaconda3/envs/eq-fault/lib/python3.6/json/__init__.py in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    177     # could accelerate with writelines in some versions of Python, at
    178     # a debuggability cost
--> 179     for chunk in iterable:
    180         fp.write(chunk)
    181 

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    428             yield from _iterencode_list(o, _current_indent_level)
    429         elif isinstance(o, dict):
--> 430             yield from _iterencode_dict(o, _current_indent_level)
    431         else:
    432             if markers is not None:

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode_list(lst, _current_indent_level)
    323                 else:
    324                     chunks = _iterencode(value, _current_indent_level)
--> 325                 yield from chunks
    326         if newline_indent is not None:
    327             _current_indent_level -= 1

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode_list(lst, _current_indent_level)
    323                 else:
    324                     chunks = _iterencode(value, _current_indent_level)
--> 325                 yield from chunks
    326         if newline_indent is not None:
    327             _current_indent_level -= 1

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    435                     raise ValueError("Circular reference detected")
    436                 markers[markerid] = o
--> 437             o = _default(o)
    438             yield from _iterencode(o, _current_indent_level)
    439             if markers is not None:

~/anaconda3/envs/eq-fault/lib/python3.6/json/encoder.py in default(self, o)
    178         """
    179         raise TypeError("Object of type '%s' is not JSON serializable" %
--> 180                         o.__class__.__name__)
    181 
    182     def encode(self, o):

TypeError: Object of type 'int64' is not JSON serializable

#### Bug/Feature Request Description

Think it is releted to
https://stackoverflow.com/questions/11942364/typeerror-integer-is-not-json-serializable-when-serializing-json-in-python

#### Output of ``featuretools.show_info()``

<details>

[paste the output of ``featuretools.show_info()`` here below this line]
>>> import featuretools as ft
>>> ft.show_info()
Featuretools version: 0.11.0
Featuretools installation directory: /home/admin/anaconda3/envs/eq-fault/lib/python3.6/site-packages/featuretools

SYSTEM INFO
-----------
python: 3.6.9.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-65-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.17.2
pandas: 0.25.2
tqdm: 4.36.1
PyYAML: 5.1.2
cloudpickle: 1.2.2
future: 0.18.0
dask: 2.6.0
distributed: 2.6.0
psutil: 5.6.3
Click: 7.0
scikit-learn: 0.21.3
pip: 19.3.1
setuptools: 41.4.0
>>>

</details>

**Comment by rwedge** [comment]
This should be fixed on master and will in the next release
