### ISSUE TITLE
Remove Python 2.7 Support from Docs

### ISSUE THREAD

**Issue by kmax12** [FeatureLabs/featuretools#797]
The documentation currently still says we support python 2.7 on the installation page. We should also make sure the python 2.7 support is removed everywhere else such as pypi and conda-forge. 

https://docs.featuretools.com/getting_started/install.html

**Comment by systemshift** [comment]
removed from the main file mentioned in the issue.
let me know where should I look further, and assign me the issue.

**Comment by systemshift** [comment]
both https://anaconda.org/conda-forge/featuretools and  https://pypi.org/project/featuretools/ do not mention 2.7

**Comment by systemshift** [comment]
The following comment mentions python 2.7. 
But this should be in a different issue to change the code base, not documentation.
https://github.com/FeatureLabs/featuretools/blob/8ba9423782691df5aea2e363a562c8d0296f6efe/featuretools/entityset/serialize.py#L95-L99
