### ISSUE TITLE
DFS `ignore_variables` not working as expected in v0.12.0

### ISSUE THREAD

**Issue by thehomebrewnerd** [FeatureLabs/featuretools#817]
#### Bug/Feature Request Description

Variables passed into the `ignore_variables` parameter during dfs are still showing up in the feature matrix output on featuretools v0.12.0. This issue is demonstrated in the attached notebook.

#### Expected Output
It is expected that any variables specified in the `ignore_variables` parameter of `ft.dfs` will not be present in the resulting feature matrix, nor will any features be generated based on these variables.

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 0.12.0
Featuretools installation directory: /Users/nate.parsons/dev/notebooks/env/lib/python3.7/site-packages/featuretools

SYSTEM INFO
-----------
python: 3.7.4.final.0
python-bits: 64
OS: Darwin
OS-release: 18.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.17.2
pandas: 0.25.1
tqdm: 4.36.1
PyYAML: 5.1.2
cloudpickle: 1.2.2
dask: 2.5.2
distributed: 2.5.2
psutil: 5.6.3
Click: 7.0
scikit-learn: 0.21.3
pip: 19.2.3
setuptools: 40.8.0

</details>

[DFS_ignore_variables.ipynb.zip](https://github.com/FeatureLabs/featuretools/files/3860935/DFS_ignore_variables.ipynb.zip)

**Comment by rwedge** [comment]
This has been addressed by #819 and should be fixed on master.  Will be in the next release.
