### ISSUE TITLE
DFS does not generate error when `ignore_variables` values are specified incorrectly

### ISSUE THREAD

**Issue by thehomebrewnerd** [FeatureLabs/featuretools#818]
#### Bug Request Description

If the user specifies the values for the `ignore_variables` parameter of `ft.dfs` in the format of `dict[str -> str]` instead of the expected format of `dict[str -> list[str]]`, no error or warning is raised and DFS execution continues, but the output contains the data for the variables that were specified in the dictionary. The behavior is demonstrated in the attached notebook.

#### Expected Output
If the parameter is specified incorrectly an error should be raised, rather than failing silently.

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 0.12.0
Featuretools installation directory: /Users/nate.parsons/dev/notebooks/env/lib/python3.7/site-packages/featuretools

SYSTEM INFO
-----------
python: 3.7.4.final.0
python-bits: 64
OS: Darwin
OS-release: 18.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.17.2
pandas: 0.25.1
tqdm: 4.36.1
PyYAML: 5.1.2
cloudpickle: 1.2.2
dask: 2.5.2
distributed: 2.5.2
psutil: 5.6.3
Click: 7.0
scikit-learn: 0.21.3
pip: 19.2.3
setuptools: 40.8.0

</details>

[DFS_ignore_variables_incorrect_param_type.ipynb.zip](https://github.com/FeatureLabs/featuretools/files/3861029/DFS_ignore_variables_incorrect_param_type.ipynb.zip)

**Comment by systemshift** [comment]
I can take a look at this.
