### ISSUE TITLE
Ugly es.plot()?

### ISSUE THREAD

**Issue by rightx2** [FeatureLabs/featuretools#828]
#### Bug/Feature Request Description

In 0.12.0, `es.plot()` shows result like this:

![Screen Shot 2019-11-23 at 11 35 56](https://user-images.githubusercontent.com/10606994/69471715-c6ab2c00-0de5-11ea-8e00-6149af91399f.png)

What's `\l` between feature names?

**Comment by systemshift** [comment]
Can you post the rest of the code so we can try to reproduce this?

**Comment by rwedge** [comment]
What version of the graphviz library are you using?

**Comment by rwedge** [comment]
Does this issue occur for any entityset you call `plot` on or only specific ones?

I cannot replicate this in my own environment.  Can you post a `conda list` or `pip freeze` of the packages that are installed?

**Comment by rightx2** [comment]
@rwedge  I upgrade graphviz to `graphviz==0.13.2` and it solves the problem. Thanks!
