### ISSUE TITLE
TypeError: invalid type promotion

### ISSUE THREAD

**Issue by jeremite** [FeatureLabs/featuretools#842]
### Bug/Feature Request Title
When I run dfs without specifying transform primitives, it works fine. But when I specified the parameters **trans_primitives** in dfs(), it fails with the error massage invalid type promotion. Is it because my featureools version is 0.12.0, but some tranform primitive are for 0.13.0? Thank youu for your help

**Comment by rwedge** [comment]
Hi @jeremite , thanks for the report.

Could you share the full stack trace of the error message and the parameters you used for the dfs call?  It would help us debug your issue.

**Comment by jeremite** [comment]
Hi @rwedge ,below is the error message, the problem is due to **trans_primitives=tfm_pmt**, tfm_pmt is a list of all the transform primitives.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-78-0f0b4a7dfd67> in <module>
      4                                 agg_primitives=agg_used,
      5                                 trans_primitives=tfm_pmt,
----> 6                                 where_primitives=whr_pmts)

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/utils/entry_point.py in function_wrapper(*args, **kwargs)
     38                     ep.on_error(error=e,
     39                                 runtime=runtime)
---> 40                 raise e
     41 
     42             # send return value

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/utils/entry_point.py in function_wrapper(*args, **kwargs)
     30                 # call function
     31                 start = time.time()
---> 32                 return_value = func(*args, **kwargs)
     33                 runtime = time.time() - start
     34             except Exception as e:

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/synthesis/dfs.py in dfs(entities, relationships, entityset, target_entity, cutoff_time, instance_ids, agg_primitives, trans_primitives, groupby_trans_primitives, allowed_paths, max_depth, ignore_entities, ignore_variables, primitive_options, seed_features, drop_contains, drop_exact, where_primitives, max_features, cutoff_time_in_index, save_progress, features_only, training_window, approximate, chunk_size, n_jobs, dask_kwargs, verbose, return_variable_types, progress_callback)
    274                                                   dask_kwargs=dask_kwargs,
    275                                                   verbose=verbose,
--> 276                                                   progress_callback=progress_callback)
    277     return feature_matrix, features

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_feature_matrix(features, entityset, cutoff_time, instance_ids, entities, relationships, cutoff_time_in_index, training_window, approximate, save_progress, verbose, chunk_size, n_jobs, dask_kwargs, progress_callback)
    278                                          pass_columns=pass_columns,
    279                                          progress_bar=progress_bar,
--> 280                                          progress_callback=progress_callback)
    281 
    282     # ensure rows are sorted by input order

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_chunk(cutoff_time, chunk_size, feature_set, entityset, approximate, training_window, save_progress, no_unapproximated_aggs, cutoff_df_time_var, target_time, pass_columns, progress_bar, progress_callback)
    374                                            ids,
    375                                            precalculated_features=precalculated_features_trie,
--> 376                                            training_window=window)
    377 
    378             id_name = _feature_matrix.index.name

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/utils.py in wrapped(*args, **kwargs)
     30         def wrapped(*args, **kwargs):
     31             if save_progress is None:
---> 32                 r = method(*args, **kwargs)
     33             else:
     34                 time = args[0].to_pydatetime()

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/calculate_feature_matrix.py in calc_results(time_last, ids, precalculated_features, training_window)
    345                                               training_window=training_window,
    346                                               precalculated_features=precalculated_features)
--> 347             matrix = calculator.run(ids, progress_callback=update_progress_callback)
    348             return matrix
    349 

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/feature_set_calculator.py in run(self, instance_ids, progress_callback)
    109                                             filter_variable=target_entity.index,
    110                                             filter_values=instance_ids,
--> 111                                             progress_callback=progress_callback)
    112 
    113         # The dataframe for the target entity should be stored at the root of

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/feature_set_calculator.py in _calculate_features_for_entity(self, entity_id, feature_trie, df_trie, full_entity_df_trie, precalculated_trie, filter_variable, filter_values, parent_data, progress_callback)
    258                 filter_values=sub_filter_values,
    259                 parent_data=parent_data,
--> 260                 progress_callback=progress_callback)
    261 
    262         # Step 4: Calculate the features for this entity.

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/feature_set_calculator.py in _calculate_features_for_entity(self, entity_id, feature_trie, df_trie, full_entity_df_trie, precalculated_trie, filter_variable, filter_values, parent_data, progress_callback)
    292 
    293         # Calculate all features that don't require the full entity.
--> 294         df = self._calculate_features(df, df_trie, not_full_entity_features, progress_callback)
    295 
    296         # Step 5: Store the dataframe for this entity at the root of df_trie, so

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/feature_set_calculator.py in _calculate_features(self, df, df_trie, features, progress_callback)
    307             representative_feature = group[0]
    308             handler = self._feature_type_handler(representative_feature)
--> 309             df = handler(group, df, df_trie, progress_callback)
    310 
    311         return df

~/dss/code-envs/python/travis/local/lib/python3.6/dist-packages/featuretools/computational_backends/feature_set_calculator.py in _calculate_transform_features(self, features, frame, _df_trie, progress_callback)
    420                 values = feature_func(*variable_data, time=self.time_last)
    421             else:
--> 422                 values = feature_func(*variable_data)
    423 
    424             # if we don't get just the values, the assignment breaks when indexes don't match

TypeError: invalid type promotion

**Comment by jeremite** [comment]
here is the dfs I used: dfs_res =  ft.dfs(target_entity='target_table',
                                entityset=es,
                                agg_primitives=agg_used,
                                trans_primitives=tfm_pmt,
                                where_primitives=whr_pmts)

**Comment by rwedge** [comment]
@jeremite , thanks for the additional info.  From the stack trace it appears the error is happening while applying one of the transform primitive functions.  My initial guess is that the data in one of the columns can't be transformed properly for some reason. 

You mentioned you are using featuretools 0.12, is it possible for you to upgrade to the latest release of featuretools (0.13.1) and check if that resolves the problem?

Beyond that,  I think the next thing to do would be to identify which primitive and columns combination is causing this error.

**Comment by jeremite** [comment]
Thank you for your answer; I removed some transform primitives and it worked finally;
Here I got another problem to bother you: when I install featuretools in another env, I went across this issue, would you give me any suggetions? Thank you

copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/psutil
Requirement already satisfied: jedi>=0.10 in /opt/dss_install/code-envs/python/travis/lib/python3.6/dist-packages (from ipython>=4.0.0->ipykernel==4.8.2->-r /opt/dss_install/tmp/pip-requirements-install/req1518047014241853746.txt (line 12)) (0.15.2)
Collecting heapdict
  Using cached HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Requirement already satisfied: wcwidth in /opt/dss_install/code-envs/python/travis/lib/python3.6/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipykernel==4.8.2->-r /opt/dss_install/tmp/pip-requirements-install/req1518047014241853746.txt (line 12)) (0.1.8)
Requirement already satisfied: parso>=0.5.2 in /opt/dss_install/code-envs/python/travis/lib/python3.6/dist-packages (from jedi>=0.10->ipython>=4.0.0->ipykernel==4.8.2->-r /opt/dss_install/tmp/pip-requirements-install/req1518047014241853746.txt (line 12)) (0.5.2)
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py): started
  Building wheel for psutil (setup.py): finished with status 'error'
  Running setup.py clean for psutil
Failed to build psutil
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=567 -DPSUTIL_LINUX=1 -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
  psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil
ERROR: featuretools 0.13.1 has requirement pandas>=0.24.1, but you'll have pandas 0.23.4 which is incompatible.
    ERROR: Command errored out with exit status 1:
     command: /opt/dss_install/code-envs/python/travis/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9toz3160/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9toz3160/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kgw1tofq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/dss_install/code-envs/python/travis/include/site/python3.6/psutil
         cwd: /tmp/pip-install-9toz3160/psutil/
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
    creating build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=567 -DPSUTIL_LINUX=1 -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/dss_install/code-envs/python/travis/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9toz3160/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9toz3160/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kgw1tofq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/dss_install/code-envs/python/travis/include/site/python3.6/psutil Check the logs for full command output.
Installing collected packages: psutil, msgpack, tblib, heapdict, zict, distributed, featuretools
    Running setup.py install for psutil: started
    Running setup.py install for psutil: finished with status 'error'
OK

**Comment by rwedge** [comment]
I've encountered an error like this before, [this stackoverflow question] may help

For your original issue, which primitives did you remove to avoid the error?  It would be good to identify the cause of the issue so we can fix it.

**Comment by rwedge** [comment]
@jeremite can you see if this issue still occurs with the latest release of Featuretools?  We've made some fixes since then that might address this problem. Feel free to re-open if this is a still a problem and you can give us a runnable example
