### ISSUE TITLE
featuretools dfs, Stream closed error issue in linux

### ISSUE THREAD

**Issue by hawksung1** [FeatureLabs/featuretools#852]
### featuretools dfs, Stream closed error issue

-----
#### Bug/Feature Request Description
featuretools dfs in linux **_SOMETIMES_** give me err Stream closed error when I set n_jobs >=2.
I guess it's a bug because in window it works fine, n_jobs=1 works fine, and even in linuxs with
n_jobs>=2 sometimes works fine or gives me result with error.

if you need full stack trace or more detail, I wrote this issue in stackoverflow also
[https://stackoverflow.com/questions/60390193/python-featuretools-dfs-stream-closed-error-issue](https://stackoverflow.com/questions/60390193/python-featuretools-dfs-stream-closed-error-issue)

#### Expected Output
always success

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 0.13.2
Featuretools installation directory: /usr/lib/python3.6/site-packages/featuretools

SYSTEM INFO
-----------
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-327.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: ko_KR.UTF-8
LOCALE: ko_KR.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.15.4
pandas: 1.0.1
tqdm: 4.42.1
PyYAML: 3.13
cloudpickle: 0.8.0
dask: 2.11.0
distributed: 2.10.0
psutil: 5.6.3
Click: 7.0
pip: 19.2
setuptools: 39.0.1

</details>

**Comment by rwedge** [comment]
@hawksung1, thanks for the bug report!

I'm trying to reproduce this on my end, if you have some example code that triggers this for you that would be a great help.

Some other clarifications that could help:
* What version of the tornado package is installed?
* Are you using `n_jobs` and `dask_kwargs` or just `n_jobs`?

**Comment by hawksung1** [comment]
1. tornado 5.1.1
2. just n_jobs
3. 3 cases, get err without result, get err with prefect result, get perfect result without err

**sample code**
I'm using below code just for test
run dfs 5times, result 2 perfect result with err, 3 perfect results

`import featuretools as ft
import pandas as pd

df = pd.read_csv(file, engine='python')

transformer_name = ["time_since_previous", "hour", "multiply_numeric"]
es = ft.EntitySet(id='es')
es.entity_from_dataframe(entity_id='data', dataframe=df, make_index=True, index='_index_')

for i in range(5):
    result, cols = ft.dfs(entityset=es, target_entity='data', trans_primitives=transformer_name, n_jobs=2, max_depth=1)
    print("     "+str(i))
print(cols)
print(result.head())
`

thanks

**Comment by rwedge** [comment]
I couldn't reproduce the exact error you reported but found a fix that remove most of the tornado errors I was encountering.  If you'd like to try out the changes yourself, you can install the branch in your environment using pip

```bash
pip uninstall featuretools
pip install git+https://github.com/FeatureLabs/featuretools.git@close-client-before-scheduler#egg=featuretools
```

Upgrading tornado and distributed to their latest versions might help as well.

**Comment by hawksung1** [comment]
WOW
I installed branch like you said. Now I have no problem and get perfect result :)
Thanks Genius.

when It will be pushed to master branch??

**Comment by rwedge** [comment]
Glad to help :)

The fix is in master branch now

We plan to release a new version of the library in the next day or so
