### ISSUE TITLE
Add link to all primitive documentation

### ISSUE THREAD

**Issue by kmax12** [FeatureLabs/featuretools#858]
We have a list of all the primitives (open source and premium) available at https://primitives.featurelabs.com/. 

We should link to this in the documentation and readme, so people can find it.

**Comment by thehomebrewnerd** [comment]
@kmax12 Do you think we should also update the primitives list website to more clearly show which primitives are available to use in the open source version? It's currently easy to tell which are premium primitives, but not so easy to tell which are available in open source.

We could add another filter button for open source only, or add some kind of display badge in the left-hand list to differentiate.

**Comment by kmax12** [comment]
ya, i think it would be nice to make it easier to identify open vs premium. my inclination would be to add both of what you suggest since they serve different roles.

**Comment by thehomebrewnerd** [comment]
> ya, i think it would be nice to make it easier to identify open vs premium. my inclination would be to add both of what you suggest since they serve different roles.

Sounds good. I added an issue in the premium primitives repo for the web page change, but I can tackle these together.

**Comment by thehomebrewnerd** [comment]
Closed via PR #860
