### ISSUE TITLE
AttributeError: type object 'MultiIndex' has no attribute 'from_frame' ? "Error Feature-tools"

### ISSUE THREAD

**Issue by alla15747** [FeatureLabs/featuretools#864]
### Bug/Feature Request Title
(Run ft.dfs command but got an unexpected error)

-----
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-5d4e660e10b2> in <module>
     36 
     37 features, feature_names = ft.dfs(entityset=es,target_entity='accounts',
---> 38                                  agg_primitives=agg_primitives,trans_primitives=trans_primitives,max_depth=1)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/featuretools/utils/entry_point.py in function_wrapper(*args, **kwargs)
     38                     ep.on_error(error=e,
     39                                 runtime=runtime)
---> 40                 raise e
     41 
     42             # send return value

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/featuretools/utils/entry_point.py in function_wrapper(*args, **kwargs)
     30                 # call function
     31                 start = time.time()
---> 32                 return_value = func(*args, **kwargs)
     33                 runtime = time.time() - start
     34             except Exception as e:

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/featuretools/synthesis/dfs.py in dfs(entities, relationships, entityset, target_entity, cutoff_time, instance_ids, agg_primitives, trans_primitives, groupby_trans_primitives, allowed_paths, max_depth, ignore_entities, ignore_variables, primitive_options, seed_features, drop_contains, drop_exact, where_primitives, max_features, cutoff_time_in_index, save_progress, features_only, training_window, approximate, chunk_size, n_jobs, dask_kwargs, verbose, return_variable_types, progress_callback)
    274                                                   dask_kwargs=dask_kwargs,
    275                                                   verbose=verbose,
--> 276                                                   progress_callback=progress_callback)
    277     return feature_matrix, features

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_feature_matrix(features, entityset, cutoff_time, instance_ids, entities, relationships, cutoff_time_in_index, training_window, approximate, save_progress, verbose, chunk_size, n_jobs, dask_kwargs, progress_callback)
    281 
    282     # ensure rows are sorted by input order
--> 283     feature_matrix = feature_matrix.reindex(pd.MultiIndex.from_frame(cutoff_time[["instance_id", "time"]],
    284                                                                      names=feature_matrix.index.names))
    285 

AttributeError: type object 'MultiIndex' has no attribute 'from_frame'

**Comment by rwedge** [comment]
Hi @alla15747 ,

`MultiIndex.from_frame` was a new method added in Pandas 0.24.0.  Try updating your pandas to a newer version

**Comment by alla15747** [comment]
@rwedge 
I tried, but that's what I get:
ERROR: featuretools 0.13.3 has requirement pandas>=0.24.1, but you'll have pandas 0.24.0 which is incompatible.

**Comment by alla15747** [comment]
**I solve this problem by the following:**
1- Increase the capacity of my VM.
2- Upgrade my pandas to 0.25.3.
3- Installing the latest version of feature tools.
