### ISSUE TITLE
Some trouble with primitive "subtract_numeric"

### ISSUE THREAD

**Issue by ZhengHaoCHeng** [FeatureLabs/featuretools#873]
### Bug/Feature Request Title
Some trouble with primitive "subtract_numeric".

#### Bug/Feature Request Description
I get some trouble when I upgrate featuretools to 0.13.4.
When I used primitive "subtract_numeric", its didn't output as my expected. 
But its work well in 0.4.1.

<pre>
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import featuretools as ft
dataset = load_iris()
X = dataset.data
iris_feature_names = dataset.feature_names
df = pd.DataFrame(X, columns=iris_feature_names)

es = ft.EntitySet(id='single_dataframe')
variable_types = {col:ft.variable_types.Numeric for col in df.columns}
es.entity_from_dataframe(entity_id='iris', 
             dataframe=df,
             make_index=True, 
             index='id',
             variable_types=variable_types)

trans_primitives=['subtract_numeric']  # 0.13.4
# trans_primitives=['subtract']        # 0.4.1
feature_matrix, feature_names = ft.dfs(entityset=es, 
     target_entity='iris', 
     max_depth=1, 
     verbose=1,
     trans_primitives=trans_primitives
)
</pre>

#### Output
Why there is not feature like **"sepal length (cm) - petal length (cm)"**. 
I think the value of "A-B" (or A/B) not always equal to "B-A" (or A/B), but "A+B"(or A×B) must equal to "B+A"(or A×B). 
And when I change  the primitive to "divide_numeric", the output are expected.

```
[<Feature: sepal length (cm)>,
 <Feature: sepal width (cm)>,
 <Feature: petal length (cm)>,
 <Feature: petal width (cm)>,
 <Feature: sepal length (cm) - sepal width (cm)>,
 <Feature: petal length (cm) - petal width (cm)>,
 <Feature: petal length (cm) - sepal width (cm)>,
 <Feature: petal width (cm) - sepal width (cm)>,
 <Feature: petal length (cm) - sepal length (cm)>,
 <Feature: petal width (cm) - sepal length (cm)>]
```

#### Expected Output
The output in 0.4.1 are listed below，that what I'm expected.  And the primitives I used in 0.4.1 is "subtract". 
```
[<Feature: sepal length (cm)>,
 <Feature: sepal width (cm)>,
 <Feature: petal length (cm)>,
 <Feature: petal width (cm)>,
 <Feature: sepal length (cm) - sepal width (cm)>,
 <Feature: sepal length (cm) - petal width (cm)>,
 <Feature: sepal length (cm) - petal length (cm)>,
 <Feature: sepal width (cm) - petal length (cm)>,
 <Feature: sepal width (cm) - petal width (cm)>,
 <Feature: petal width (cm) - sepal width (cm)>,
 <Feature: petal length (cm) - sepal length (cm)>,
 <Feature: petal width (cm) - petal length (cm)>,
 <Feature: petal length (cm) - petal width (cm)>,
 <Feature: sepal width (cm) - sepal length (cm)>,
 <Feature: petal width (cm) - sepal length (cm)>,
 <Feature: petal length (cm) - sepal width (cm)>]
```

**Comment by rwedge** [comment]
Hi @ZhengHaoCHeng, thanks for the question!

We have an option to configure `SubtractNumeric` to function like the old  `Subtract` primitive.

Instead of referring to the primitive by its string name like this:
```python
trans_primitives=["subtract_numeric"],
```
Create an instance of the SubtractNumeric primitive class, and set the optional `commutative` argument to `False`
```python
trans_primitives=[ft.primitives.SubtractNumeric(commutative=False)]
```
When I did that, DFS created 16 features, including "sepal length (cm) - petal length (cm)"

**Comment by ZhengHaoCHeng** [comment]
> Hi @ZhengHaoCHeng, thanks for the question!
> 
> There is an option to configure `SubtractNumeric` to function like the old `Subtract` primitive.
> 
> Instead of referring to the primitive by its string name like this:
> 
> ```python
> trans_primitives=["subtract_numeric"],
> ```
> 
> Create an instance of the SubtractNumeric primitive class, and set the optional `commutative` argument to `False`
> 
> ```python
> trans_primitives=[ft.primitives.SubtractNumeric(commutative=False)]
> ```
> 
> When I did that, DFS created 16 features, including "sepal length (cm) - petal length (cm)"

thank you.
