### ISSUE TITLE
get_names() and get_name() do not return the same value if num_of_output features is 1

### ISSUE THREAD

**Issue by gsheni** [FeatureLabs/featuretools#874]
#### Bug Request Description
- `get_names` and `get_name` are two functions we use to get the feature name (corresponding to the 
column names in the feature matrix).
- If the `number_output_features` is 1 for a feature, they should return the same thing (a list with 1 item, that is the same as the `get_name`. 
- Related [issue](792) **But not the same**

#### Current Behavior
```python
import featuretools as ft
es = ft.demo.load_mock_customer(return_entityset=True)
_, feature_defs = ft.dfs(entityset=es,
                                      target_entity="customers",
                                      agg_primitives=[],
                                      trans_primitives=["month"],
                                      max_depth=1)
print(feature_defs[1].get_name())
print(feature_defs[1].get_names())
```

##### Current Output
```python
 'MONTH(join_date)'
['MONTH(join_date)[0]']
```
#### Expected Output
```python
 'MONTH(join_date)'
['MONTH(join_date)']
```

**Comment by rwedge** [comment]
I think `Feature.get_feature_names` already has this behavior

```python
    def get_feature_names(self):
        n = self.number_output_features
        if n == 1:
            names = [self.get_name()]
        else:
            names = self.get_names()
        return names
```

**Comment by thehomebrewnerd** [comment]
@gsheni After some discussion, we are going to review the naming methods in more detail to address the issue you have highlighted as well as the issue in #792 before we implement a fix.

To summarize the current state: Calling `Feature.get_name()` will return the name of the main base feature, and `Feature.get_feature_names()` will return a list of all of feature output names - a single item list in the case of a single output feature or a multi item list in the case of a multi output feature.

If you call `Feature.get_feature_names()` on a single output feature, the single item in the list will have the same name as the main base feature. For multi-output features a numeric suffix will appended to the base feature name.

Currently `Feature.get_names()` and Feature.get_feature_names()` will return the same list for a multi output feature. There is a difference for single output features as you have pointed out in this issue. Going forward there is probably not a need for both of those methods to exist in the public API.

For now getting the base feature name through `Feature.get_name()` or getting a list of output names through `Feature.get_feature_names()` is the way to go, while we consider a better long term solution to clean this up.

**Comment by thehomebrewnerd** [comment]
Is there any reason we can't just remove `Feature.get_names()` completely and move the logic for setting `Feature._names` into `Feature.get_feature_names()`? 

That would leave us with two public methods for getting feature names:
- `Feature.get_name()` to get the single string name of the base feature (which will also be the name of the feature in the case of a single output feature)
- `Feature.get_feature_names()` to get a list of all the new feature names that will be generated. For single output features, this will be a single item list, and for multi output features all the feature names will be in the list.
