### ISSUE TITLE
Improve memory consumption by downsizing data type for encoded features

### ISSUE THREAD

**Issue by martinhjel** [FeatureLabs/featuretools#875]
Is there any reason why the data type of the one-hot-encoded feature columns is not `bool` or `np.uint8` in the `encode_features` method? E.g. the latter one is the default data type for the pandas method [get_dummies](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html).

https://github.com/FeatureLabs/featuretools/blob/d0a43acf5f0b88e001479c738353897d7a6891af/featuretools/synthesis/encode_features.py#L136

**Comment by rwedge** [comment]
No reason, this would be a good change to make.

**Comment by martinhjel** [comment]
Good. And for future reference, I see that tensorflow 2.1.0 throws  
`ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type bool).` when using `bool` type. So `np.uint8` should be the way to go.
