### ISSUE TITLE
Dask vs Pandas: Predict Next Purchase Comparison

### ISSUE THREAD

**Issue by rwedge** [FeatureLabs/featuretools#881]
We need to make two versions of the predict next purchase demo using both Dask dataframes and Pandas dataframes.  There should be a clear starting point where the two demos diverge and we can compare timings from that point forward.

**Comment by thehomebrewnerd** [comment]
A comparison was made between the original predict next purchase notebook using a Dask Bag approach and the new featuretools approach. The comparison includes only the primitives that are currently supported in the Dask implementation, and does not use the `training_window` parameter which is not currently supported for Dask dataframes. The output was compared to confirm the two feature matrices were equal after accounting for row/column sort order differences.

A summary of the total times for each approach are listed below:

**Original Notebook**
- Preprocessing files: 555 seconds
- Loading sample data to generate features: 11 seconds
- Creating label times: <1 second
- Running DFS: <1 second
- Computing feature matrix and save to CSV: 402 seconds
- TOTAL: 969 seconds

**New Dask Implementation**
- Preprocessing files: 766 seconds
- Creating entityset, normalizing, and adding last time indexes: <1 second
- Creating label times: 43 seconds
- Running DFS: 1 second
- Computing feature matrix and save to CSV: 476 seconds
- TOTAL: 1287 seconds
