### ISSUE TITLE
Document functionality supported by dask implementation

### ISSUE THREAD

**Issue by rwedge** [FeatureLabs/featuretools#885]
Actually, we should document functionality not supported by dask.

Taking notes here: https://docs.google.com/document/d/1E8m2VK_Au-ra1H-s3bFo1hsXagssoevyPKN4VN_D9Bo/edit#heading=h.acxo96jnpc5w

**Comment by kmax12** [comment]
Actually, we should document functionality not supported by dask.

TODO: add google docs link

**Comment by thehomebrewnerd** [comment]
Additional limitations to include in documentation:
- If issue #978 is not resolved prior to release, document that Dask EntitySets do not support `add_interesting_values()`

**Comment by thehomebrewnerd** [comment]
Closed by #965
