### ISSUE TITLE
Primitives that are unsupported in Dask

### ISSUE THREAD

**Issue by kmax12** [FeatureLabs/featuretools#904]

**Comment by frances-h** [comment]
The Dask implementation currently does not support the following primitives:

Transform Primitives:
- CumMean
- EqualScalar
- NotEqualScalar
- Equal (related to #845)
- NotEqual (related to #845 )

Aggregation Primitives:
- Mode
- Median
- NMostCommon
- Skew
- Entropy
- First
- Last
- TimeSinceFirst
- TimeSinceLast
- Trend

**Comment by thehomebrewnerd** [comment]
I added a few new transform primitives to the list above. We might be able to fix Latitude and Longitude fairly easily, but haven't looked into it yet.

**Comment by thehomebrewnerd** [comment]
When completed issue #962 will allow users to obtain a list of features that are supported by the Dask implementation. Additionally, supported primitives will be documented in the updates associated with #885.
