### ISSUE TITLE
Run full unit tests with dask

### ISSUE THREAD

**Issue by kmax12** [FeatureLabs/featuretools#905]
* How do we run the test suite twice (w/ dask and pandas) without duplicated code?
* We can mark certain tests as expect to fail
* We should also be able to repeat easily as we support other types of dataframes like Koalas or cuDF

**Comment by kmax12** [comment]
from @frances-h: https://docs.pytest.org/en/latest/parametrize.html

**Comment by rwedge** [comment]
This been achieved in #999, albeit with xfails for testing features unsupported with dask.  Some additional cleanup is needed (like #1023) but the unit tests run with dask now.
