### ISSUE TITLE
Equal, NotEqual primitives error when comparing categorical columns with different categories

### ISSUE THREAD

**Issue by hawksung1** [FeatureLabs/featuretools#922]
### Bug/Feature Request Title
(dfs equal, categorical type err)

-----
*dfs trans_primitives 'equal' function makes err always with 2 or more categorical column table.
full code [here](https://stackoverflow.com/questions/61381094/featuretools-dfs-equal-categorical-type-err)

#### Bug/Feature Request Description
*{TypeError}Categoricals can only be compared if 'categories' are the same. Categories are different lengths*

#### Expected Output
table with new column, function 'equal' worked to 'category' column
OR
table with new column, function 'equal' ignore 'category' column

anyway no err

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 0.13.4
Featuretools installation directory: c:\users\hyun\pycharmprojects\featuretools\venv\lib\site-packages\featuretools
SYSTEM INFO
-----------
python: 3.8.1.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
</details>

**Comment by rwedge** [comment]
Thanks for the report and code example, @hawksung1.  I encountered a similar error using the NotEqual primitive.
