### ISSUE TITLE
Functionality - Creating custom primitive using classes

### ISSUE THREAD

**Issue by mohkar123** [FeatureLabs/featuretools#927]
Is there a way to create a custom primitive from a class of functions? For example - If I have class A with function B, C and D, can I define the class as an agg primitive to call all the functions? That way all functions need not have its own custom primitive and just the class can be defined as so.

**Comment by rwedge** [comment]
Hi @mohkar123,

Not really.  Featuretools expects a custom primitive to have a `get_function` method that returns a single primitive function.  It wouldn't know to use B, C, and D as primitive functions.

Featuretools supports creating primitives that have multiple output columns (documentation on that topic [here](https://docs.featuretools.com/en/stable/guides/advanced_custom_primitives.html#features-with-multiple-outputs)), but that is more for primitive functions that naturally return multiple values.  In theory you could create a custom primitive that applies all 3 functions to the input data as a combined function, but I wouldn't recommend that approach as it runs counter to the idea of a primitive being a single function.   The ability to apply just a B, C, or D alone would be lost, and if the individual functions need different inputs DFS may create duplicate output features.

I'll close this issue as I hope I've answered your question but feel free to re-open if you would like to discuss more or need more clarification.
