### ISSUE TITLE
Parameterize Inclusive Cutoff Times

### ISSUE THREAD

**Issue by jeff-hernandez** [FeatureLabs/featuretools#942]
Data at cutoff times are currently included in feature calculations. We can make this a parameter to provide users the option to exclude the data.

#### Software Design
The parameter `include_cutoff_time` would be added in `dfs` and `calculate_feature_matrix`  to control whether data at cutoff times are included in feature calculations.

```python
ft.dfs(
    ...
    include_cutoff_time=True,
)
```

When using cutoff times with training windows, the training window start time (left endpoint) should be excluded from feature calculations when the cutoff time (right endpoint) is included. This will avoid overlap from consecutive training windows. Similarly, the training window start time should be included when the cutoff time is excluded.

#### Test Cases

There should be test cases that check feature calculations when:

- A training window is not used and cutoff times are inclusive.
- A training window is not used and cutoff times are exclusive.
- A training window is used and cutoff times are inclusive.
- A training window is used and cutoff times are exclusive.

**Comment by rwedge** [comment]
Fixed in #959
