### ISSUE TITLE
Suggestions for Primitives to be used for DFS

### ISSUE THREAD

**Issue by siddhant-bharti** [FeatureLabs/featuretools#972]
It would be super exciting to see recommendations for the primitives to be used for a certain type of dataset that FeatureTool is working upon.

**Comment by rwedge** [comment]
Hi @siddhant-bharti, thanks for the feedback.

This is something we would like to add, in fact we already have an issue discussing it, #939!

I'm going to close this issue since it's a duplicate, let's keep the discussion in #939.
